site_name: Betz Engineering
site_description: Full stack hard- and software design
site_url: https://betz-engineering.ch

theme:
  name: material
  palette:
    primary: black
    accent: light green
  font:
    text: Ubuntu
  logo: pics/be_logo.png
  favicon: pics/be_logo.png
  features:
    - navigation.path
    - navigation.indexes

exclude_docs: |
  !.well-known

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Open Hardware:
    - open_hardware/index.md
    - open_hardware/ui_board_1u.md
  - about.md

extra_css:
  - extra.css

plugins:
  - search:
      enabled: false
  - glightbox

